language: python

python:
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "nightly" # currently points to 3.7-dev

install:
  - pip install -r requirements
  - pip install codeclimate-test-reporter
  - pip install coveralls

script:
  - PYTHONPATH=. py.test
